config/routes.rb
Rails.application.routes.draw do

  resources :games
  root to: 'games#splash'
  get 'welcome' => 'games#welcome'
  get 'finished' => 'games#finished'
  resources :choices

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def splash
    #all the other apps we would build.
  end

  def welcome
    @parent_session_id = params[:parent_session_id]
    if @parent_session_id
      redirect_to new_game_path(parent_session_id: @parent_session_id) and return
    end
  end

  def finished
    @session = current_session
  end

  def new
    @parent_session_id = params[:parent_session_id]
    @parent_session = get_session(params[:parent_session_id]) unless params[:parent_session_id].to_s == ""
  end

  def create
    choices = choice_template

    @parent_session = get_session(params[:parent_session_id]) unless params[:parent_session_id].to_s == ""

    session = {}
    session[:id] = SecureRandom.uuid
    if @parent_session
      session[:name] = @parent_session[:name]
      session[:color] = @parent_session[:color]
      session[:parent_session_id] = @parent_session[:id]
      session[:iteration] = @parent_session[:iteration] + 1
      # FOR DEMO - crank up environmental issues on second gen
      session[:initial_environment] = @parent_session[:environment] * 2.5
    else
      session[:name] = params[:session_name]
      session[:color] = params[:session_color]
      session[:iteration] = 1
      session[:initial_environment] = 1
    end
    session[:starting_money] = 1000
    session[:money] = session[:starting_money]
    session[:environment] = session[:initial_environment]
    session[:total_miles] = choices.sum{|c| c[:location][:mileage] }
    session[:miles_remaining] = session[:total_miles]
    session[:pending_choices] = choices
    session[:completed_choices] = []

    # now persist session
    store_session(session)
    redirect_to new_choice_path(session_id: session[:id])
  end

  protected

  def choice_template
    [
      {
        id: 1,
        location: {
          name: "San Francisco, CA",
          lat: "37.8",
          long: "-122.4",
          mileage: 575,
          type: "start"
        },
        description: "First, you have to pick a rental car! Choose carefully, because you'll also be paying for gas each day depending on the fuel economy of your vehicle!",
        options: [
          {
            id: 1,
            description: "Prius",
            outcome: {
              car: {
                name: "prius",
                gas_cost: 20
              },
              cost: 200
            }
          },
          {
            id: 2,
            description: "Camry",
            outcome: {
              car: {
                name: "camry",
                gas_cost: 75
              },
              cost: 150
            }
          },
          {
            id: 3,
            description: "Volt",
            outcome: {
              car: {
                name: "volt",
                gas_cost: 0
              },
              cost: 400
            }
          }
        ]
      },
      {
        id: 2,
        location: {
          name: "Las Vegas, NV",
          lat: "36.1",
          long: "-115.2",
          mileage: 750
        },
        description: "No one can drive all day (what is this a hackathon?), so it's time to find a place to crash. Where will you stay tonight?",
                options: [
          {
            id: 1,
            description: "I'll just find a hotel.",
            outcome: {
              cost: 125,
              cost_impact: 2,
              environment: 4
            }
          },
          {
            id: 2,
            description: "Air B'n'B has yet to let me down!",
            outcome: {
              cost: 75,
              cost_impact: 1.5,
              environment: 1
            }
          },
          {
            id: 3,
            description: "I'll see if there's a local hostel at the next city.",
            outcome: {
              cost: 100,
              cost_impact: 1.5,
              environment: 2
            }
          },
          {
            id: 4,
            description: "Let's buy gear go camping!",
            outcome: {
              cost: 500,
              cost_impact: 0,
              environment: 3
            }
          }
        ]
      },
      {
        id: 3,
        location: {
          name: "Denver, CO",
          lat: "39.7",
          long: "-105",
          mileage: 250
        },
        description: "It's dinner time, and you've been driving for six hours straight. It's time to eat, but where will you go?",
        options: [
          {
            id: 1,
            description: "McDonald's is fine. No use in being picky.",
            outcome: {
              cost: 50,
              cost_impact: 3,
              environment: 3
            }
          },
          {
            id: 2,
            description: "I'll find a co-op and get some fresh groceries.",
            outcome: {
              cost: 75,
              cost_impact: 2,
              environment: 1
            }
          },
          {
            id: 3,
            description: "There's a great farm-to-table restaurant at the next exit!",
            resource_impact_description: <<-DESC ,
            DESC
            environmental_impact_description: <<-DESC ,
              Local food is not only healthier and tastier, it is also better for the
              environment because fewer transport miles equal fewer transmissions. According
              to a study conducted by the Leopold Center for Sustainable Agriculture at Iowa State University,
              food travels 1,500 miles on average from farm to customer while locally sourced food travels an average
              of 44.6 miles. The same study found that the conventional food distribution system uses 4 to 17 times more
              fuel and emits 5 to 17 times more CO2 than local and regional systems.
              However, the environmental impact of food depends not only on how long it travels, but also on how it is
              transported. Ton for ton, trains are far more efficient at moving freight than trucks are. This means that
              the greenhouse gases associated with transporting potatoes trucked in from 100 miles away is the same as those
              associated with potatoes shipped in by rail from 1,000 miles away.
            DESC
            outcome: {
              cost: 125,
              cost_impact: 2,
              environment: 2
            }
          }
        ]
      },
      {
        id: 4,
        location: {
          name: "Chicago, IL",
          lat: "41.2",
          long: "-87.6",
          mileage: 1450
        },
        description: "You're getting thirsty and you're out of water, what will you buy to drink?",
        options: [
          {
            id: 1,
            description: "Buy 2 whole cases of bottled water at Costco",
            resource_impact_description: <<-DESC ,
              2- 24 packs of bottled water cost $12. It will last you 8 days,
              but the weight that the cases of water adds to your car will affect your fuel economy.
            DESC
            environmental_impact_description: <<-DESC ,
              The weight that the case of water adds to your car will affect your fuel economy which
              affects the amount of gas you are using. Every time you buy a plastic drinking bottle,
              you are also using some of the world's limited supply of oil--manufacturers use petroleum
              to make and transport plastic products. Plastic bottle production in the U.S. requires millions
              of barrels of crude oil annually. Beverage companies then use fuel to transport the bottles all
              over the world, polluting the atmosphere in the process.
            DESC
            outcome: {
              cost: 40,
              cost_impact: 4,
              environment: 3
            }
          },
          {
            id: 2,
            description: "Buy a stainless steel water bottle and fill it at the tap",
            resource_impact_description: <<-DESC ,
              The stainless steel bottle costs $12.99. Can refill water for free.
            DESC
            environmental_impact_description: <<-DESC ,
              You save the fuel it costs to create water bottles and recycle them and
              the extra gas it takes to carry cases of water in your car.
            DESC
            outcome: {
              cost: 80,
              cost_impact: 2,
              environment: 1
            }
          },
          {
            id: 3,
            description: "Buy some 2 liters of soda instead",
            resource_impact_description: <<-DESC ,
              A 24 pack of bottled water costs $5.99. It will last you 4 days,
              but the weight that the cases of water adds to your car will affect your fuel economy
            DESC
            environmental_impact_description: <<-DESC ,
              Although you are using less water bottles than if you had bought 2 cases, the amount
              of fuel that it takes the companies that produce them to transport the products still
              takes the same amount of gas. The weight that the case of water adds to your car will
              affect your fuel economy which affects the amount of gas you are using. Every time you
              buy a plastic drinking bottle, you are also using some of the world's limited supply of
              oil manufacturers use petroleum to make and transport plastic products. Plastic bottle
              production in the U.S. requires millions of barrels of crude oil annually. Beverage
              companies then use fuel to transport the bottles all over the world, polluting the atmosphere in the process.
            DESC
            outcome: {
              cost: 60,
              cost_impact: 2.5,
              environment: 2.5
            }
          }
        ]
      },
      {
        id: 5,
        location: {
          name: "Pittsburg, PA",
          lat: "40.3",
          long: "-76.9",

app/helpers/game_helper.rb
module GameHelper
end

app/views/games/finished.erb
<% if @session[:pending_choices].length > 0 %>
	<h2>Oh no! You Didn't Quite Make it!</h2>
	<div class="small-12 medium-8 columns">
		<div class="small-12 panel radius">
			<p>Sorry <%= @session[:name] %>!</p>
			<p>After <%= @session[:completed_choices].length %> days on the road, you don't have enough money to continue.</p>
			<%= link_to "Give it Another Go", welcome_path, {class: "button red radius"}  %>
			<div class="right">
				<a target="_blank" href="https://twitter.com/share?text=I made it to day <%= @session[:completed_choices] %>! How far can you make it?"><i class="fa fa-twitter-square"></i></a>
				<a onclick="FB.ui({method: 'feed', link: 'http://www.aninconvenientapp.com/', caption: 'I made it to day <%= @session[:completed_choices] %>! How far can you make it?'}, function(response){});"><i class="fa fa-facebook-square"></i></a>
			</div>
		</div>
	</div>
	<div class="small-12 medium-4 columns">
		<div class="small-12 panel radius">
			<h6>Money: $<%= @session[:money] %></h6>
		</div>
	</div>

<% else %> 
	<h2>Congratulations! You Made It!</h2>
	<div class="small-12 medium-8 columns">
		<div class="small-12 panel radius">
			<p>Great job <%= @session[:name] %>!</p>
			<p>You made it to New York with $<%= @session[:money] %> left. But keep in mind, this is about more than just you. The decisions you made will have lasting effects on all of the future generations.</p>
			<p>To give you the chance to see what those effects might be, try playing as the next generation!</p>
			<%= link_to "Proceed to the next generation", welcome_path(parent_session_id: @session[:id]), {class: "button red radius"}  %>
			<div class="right">
				<a target="_blank" href="https://twitter.com/share?text=I made it to New York with $<%= @session[:money] %> left! How far can you make it?"><i class="fa fa-twitter-square"></i></a>
				<a onclick="FB.ui({method: 'feed', link: 'http://www.aninconvenientapp.com/', caption: 'I made it to New York with $<%= @session[:money] %> left! How far can you make it?'}, function(response){});"><i class="fa fa-facebook-square"></i></a>
			</div>
		</div>
	</div>
	<div class="small-12 medium-4 columns">
		<div class="small-12 panel radius">
			<h6>Money: $<%= @session[:money] %></h6>
		</div>
	</div>
<% end %>
<script>
      window.fbAsyncInit = function() {
        FB.init({
          appId      : '780321872007889',
          xfbml      : true,
          version    : 'v2.0'
        });
      };

      (function(d, s, id){
         var js, fjs = d.getElementsByTagName(s)[0];
         if (d.getElementById(id)) {return;}
         js = d.createElement(s); js.id = id;
         js.src = "//connect.facebook.net/en_US/sdk.js";
         fjs.parentNode.insertBefore(js, fjs);
       }(document, 'script', 'facebook-jssdk'));
</script>

app/views/games/new.erb
<div class="small-12 medium-7 columns">
	<% if @parent_session.nil? %>
	<div class="small-12 panel radius">
		<h1 class="text-center">Create Your player!</h1>
		<%= form_tag("/games", method: "post") do %>
          <%= hidden_field_tag :parent_session_id, @parent_session_id %>
		  <div class="small-9 columns">
		  	<%= label_tag(:session_name, "Player Name") %>
		  	<%= text_field_tag(:session_name) %>
		  </div>
		  <div class="small-3 columns">
			  <%= label_tag(:session_color, "Car Color") %>
			  <%= text_field_tag(:session_color, "#FFFFFF") %>
		  </div>
		  <div class="text-center"><%= submit_tag("Hit the Road!", {class: "button red radius"}) %></div>
		<% end %>

	<% else %>
	<div data-alert class="alert-box warning radius text-center">
	<% year = 2014 + (@parent_session[:iteration])*20 %>
	  <h3>Time Travel Alert!</h3>
	  <p>The year is now <%= year %> and your descendants are doing the same trip that you did back in 2014. Keep an eye out for changes and question mark icons where you can learn more about why these changes happened.</p>
	  <p>For the sake of comparison, your previous choices will be underlined.</p>
	  <a href="#" class="close">&times;</a>
	</div>
	<div class="small-12 panel radius">
		<h1 class="text-center">Generation <%= @parent_session[:iteration]+1 %>!</h1>
		<%= form_tag("/games", method: "post") do %>
          <%= hidden_field_tag :parent_session_id, @parent_session_id %>
		  <div class="small-12 columns">
		  	<p class="text-center">Name: <%= @parent_session[:name] %> <%= 'I'*(@parent_session[:iteration]+1) %></p>
		  </div>
		  <div class="text-center"><%= submit_tag("Hit the Road!", {class: "button red radius"}) %></div>
		<% end %>
	<% end %>
	</div>
</div>
<div class="small-12 medium-5 columns">
	<div class="small-12 panel radius">
		<ul>
			<li>Starting Location: San Francisco, CA</li>
			<li>Ending Location: New York, NY</li>
			<li>Total Distance: 3,725 mi.</li>
			<li>Starting money: $1,000</li>
		</ul>
	</div>
</div>
<script>
	$("#session_color").spectrum({
	    color: "#fff"
	});
</script>

app/views/games/new.haml
<%= form_tag("/games", method: "post") do %>
  <%= label_tag(:player_name, "Name") %>
  <%= text_field_tag(:player_name) %>
  <br/>
  <%= label_tag(:player_color, "Color") %>
  <%= text_field_tag(:player_color) %>
  <br/>
  <% @cars.each do |car| %>
    <%= radio_button_tag(:player_car, car.name.downcase) %>
    <%= label_tag("player_car_#{car.name.downcase}", car.name) %>
    <br/>
  <% end %>
  <%= submit_tag("Hit the Road!") %>
<% end %>

app/views/games/splash.html.erb
<h1 class="text-center">An Inconvenient App</h1>
<div class="row" data-equalizer>
	<div class="small-12 medium-4 columns" data-equalizer-watch>
		<div class="app-icon">
			<a href="/welcome"><i class="fa fa-car"></i></a>
		</div>
		<h3 class="text-center">
			<a href="/welcome">Road Trip</a>
		</h3>
	</div>
	<div class="small-12 medium-4 columns disabled" data-equalizer-watch>
		<div class="app-icon">
			<a href="#"><i class="fa fa-home"></i></a>
		</div>
		<h3 class="text-center">
			<a href="#">House Builder</a>
		</h3>
	</div>
	<div class="small-12 medium-4 columns disabled" data-equalizer-watch>
		<div class="app-icon">
			<a href="#"><i class="fa fa-child"></i></a>
		</div>
		<h3 class="text-center">
			<a href="#">Parenting</a>
		</h3>
	</div>
</div>
<hr />
<h1 class="text-center">Our Theory of Change</h1>
<div class="row" data-equalizer>
	<div class="small-12 medium-4 columns" data-equalizer-watch>
		<div class="app-icon">
			<a href="#" data-reveal-id="dataModal"><i class="fa fa-database"></i></a>
		</div>
		<h3 class="text-center">
			<a href="#" data-reveal-id="dataModal">Data</a>
		</h3>
	</div>
	<div class="small-12 medium-4 columns" data-equalizer-watch>
		<div class="app-icon">
			<a href="#" data-reveal-id="storyModal"><i class="fa fa-bullhorn"></i></a>
		</div>
		<h3 class="text-center">
			<a href="#" data-reveal-id="storyModal">Story</a>
		</h3>
	</div>
	<div class="small-12 medium-4 columns" data-equalizer-watch>
		<div class="app-icon">
			<a href="#" data-reveal-id="changeModal"><i class="fa fa-globe"></i></a>
		</div>
		<h3 class="text-center">
			<a href="#" data-reveal-id="changeModal">Change</a>
		</h3>
	</div>
</div>
<div id="dataModal" class="reveal-modal" data-reveal>
  <h2>Data? What Data?</h2>
  <p class="lead">Data helps us tell effective stories...</p>
  <p>Although we haven't had to hook up robust API's to this app in its current iteration, don't think we're just making up facts. Hours of this hackathon have gone into researching the impacts of the choices we present in the game. Plus, we've designed the mechanics so that more specific climate models can easily be inserted to give the game a different set of feedback loops, and thus very different priorities.</p>
  <a class="close-reveal-modal">&#215;</a>
</div>
<div id="storyModal" class="reveal-modal" data-reveal>
  <h2>Data Alone is not Enough</h2>
  <p class="lead">You have to tell a great story...</p>
  <p>Stories lend a set of human values and contexts for decision simulators. They give decisions emotional resonance, and they allow the audience to reveal their viewpoint of the world without feeling defensive. For this hackathon, we chose to tell one story: the story of a roadtrip. But there are plenty of other great stories out there that come with their own set of decisions and lessons to be learned. There's a lot of room for a set of apps like this to grow.</p>
  <a class="close-reveal-modal">&#215;</a>
</div>
<div id="changeModal" class="reveal-modal" data-reveal>
  <h2>Everyone Talks it, Very Few Walk it</h2>
  <p class="lead">Change comes from people...</p>
  <p>And people make change using their inner narratives. Everyone knows heros can make a difference. The challenge is not to give people super powers, but to give them a personal narrative that empowers them to use the powers they already have.</p>
  <a class="close-reveal-modal">&#215;</a>
</div>

app/views/games/welcome.erb
<h2>Welcome to An Inconvenient App:Road Trip Edition!</h2>
<p> It's summer and adventure awaits you! For the next few minutes, your mission is to fullfill the classic American coming-of-age tale: the cross-country road trip.</p>
<% image = '/liberty.jpg' %>
<% if !(@parent_session.nil?) %>
	<% image = '/liberty_warmed_1.jpg' if(@parent_session[:environment] > 15) %>
	<% image = '/liberty_warmed_1.jpg' if(@parent_session[:environment] > 30) %>
<% end %>
<img src="<%= image %>"/>
<p> You'll start with $1,000 and your goal is to make it from San Francisco to New York in five days. Sound easy? Let's find out. The money is yours to spend, but be careful: if you run out of money, your trip is over!</p>
<%= link_to "Next Step: Create Your Player", new_game_path(parent_session_id: @parent_session_id), {class: "red button radius right"} %>

app/views/games/welcome.haml
<h2>Welcome to the game</h2>
<%= link_to "Start", new_game_path %>